version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/documenta
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=documenta
    ports:
      - "5432:5432"
  
volumes:
  postgres_data:
  