"""empty message

Revision ID: 0a70cf04550a
Revises: 352fe3b21681
Create Date: 2024-10-14 10:53:39.658456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a70cf04550a'
down_revision = '352fe3b21681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('cubo',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('categoria_nome', sa.String(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('contrato_nome', sa.String(), nullable=False),
    sa.Column('colunas', sa.String(), nullable=False),
    sa.Column('prazo', sa.String(), nullable=False),
    sa.Column('perfil', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('perfil',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_nome', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('empresa_nome')

    op.drop_table('perfil')
    op.drop_table('cubo')
    op.drop_table('categoria')
    # ### end Alembic commands ###
