"""empty message

Revision ID: 10e43ce96e22
Revises: 2395ae8c11a3
Create Date: 2024-10-16 08:58:22.190480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e43ce96e22'
down_revision = '2395ae8c11a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_delete_users', sa.Boolean(), nullable=False))
        batch_op.drop_column('can_delete_uses')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('perfil_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('perfil_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_delete_uses', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('can_delete_users')

    # ### end Alembic commands ###
