"""empty message

Revision ID: 12626d0ffb5f
Revises: 156ed65e09f0
Create Date: 2024-10-24 11:52:29.747651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12626d0ffb5f'
down_revision = '156ed65e09f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###
