"""empty message

Revision ID: 161220d363f0
Revises: 647982f8d148
Create Date: 2024-10-03 12:00:08.135941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161220d363f0'
down_revision = '647982f8d148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('file')

    # ### end Alembic commands ###
