"""empty message

Revision ID: 45c1866befe8
Revises: 12626d0ffb5f
Create Date: 2024-12-11 08:53:04.590055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c1866befe8'
down_revision = '12626d0ffb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cubo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasta_drive', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cubo', schema=None) as batch_op:
        batch_op.drop_column('pasta_drive')

    # ### end Alembic commands ###
