"""empty message

Revision ID: 647982f8d148
Revises: 
Create Date: 2024-10-03 11:56:06.026853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647982f8d148'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('documento',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('anexo', sa.String(), nullable=False),
    sa.Column('perfil', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('empresa',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('user',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('perfil', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('empresa')
    op.drop_table('documento')
    op.drop_table('contrato')
    # ### end Alembic commands ###
