"""empty message

Revision ID: 7fc0e17c075b
Revises: 966bf00c4055
Create Date: 2024-10-17 08:38:12.938603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc0e17c075b'
down_revision = '966bf00c4055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato_nome', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('categoria_nome', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_column('categoria_nome')
        batch_op.drop_column('contrato_nome')

    # ### end Alembic commands ###
