"""empty message

Revision ID: 966bf00c4055
Revises: 495fa1df2a35
Create Date: 2024-10-17 08:04:24.448165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966bf00c4055'
down_revision = '495fa1df2a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.String(), nullable=False))
        batch_op.drop_column('perfil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###
