"""empty message

Revision ID: 9bf9b23eb46c
Revises: f3094601ec30
Create Date: 2024-10-08 15:49:52.595558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf9b23eb46c'
down_revision = 'f3094601ec30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###
