"""empty message

Revision ID: 9e6c18da07ee
Revises: 7fc0e17c075b
Create Date: 2024-10-17 13:22:12.367619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6c18da07ee'
down_revision = '7fc0e17c075b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cubo', schema=None) as batch_op:
        batch_op.drop_column('colunas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cubo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colunas', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
