"""empty message

Revision ID: f3094601ec30
Revises: d71f022ce3cc
Create Date: 2024-10-04 13:58:19.783310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3094601ec30'
down_revision = 'd71f022ce3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('obs', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('contrato_id', sa.Integer(), nullable=False))
        batch_op.alter_column('anexo',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('chave')

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.alter_column('anexo',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('contrato_id')
        batch_op.drop_column('obs')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
